### ISSUE TITLE
Selectbox open to outside of screen

### ISSUE THREAD

**Issue by volcanioo** [Blobfolio/blob-select#2]
<img width="412" alt="screen shot 2018-04-12 at 12 07 20" src="https://user-images.githubusercontent.com/14016028/38667427-139a1ba6-3e4a-11e8-9594-6c1d54ace1ae.png">

If I am open selectbox in footer, selectbox container not open upside, always open downside.

I fix in this way:

```js
let allSelect_ = document.querySelectorAll('.blobselect');
for (var i = 0; i < allSelect_.length; i++) {
    let selects = document.getElementsByClassName('blobselect')[i];
    selects.addEventListener("click", function (event, element) {
        let _restSelcts = document.getElementsByClassName('blobselect');
        for (var j = 0; j < _restSelcts.length; j++) {
            _restSelcts[j].classList.remove("upper");
        }
        let _screenHeight = document.getElementsByTagName('body')[0].clientHeight;
        let _thisTopOfPage = event.clientY;
        let _elementHeight = selects.parentElement.getElementsByClassName('blobselect-items')[0].clientHeight;
        if ((_thisTopOfPage+_elementHeight) > (_screenHeight-(_thisTopOfPage+_elementHeight+40))) {
            selects.classList += " upper";
        }
    })
}
```

I create a upper class and change top, bottom position in this class. And i fixed.
Does anybody have any other proposals?
Anytime, if you want look this demo: https://www.cssscript.com/demo/select-box-replacement-blob-select/

**Comment by joshstoik1** [comment]
You've got the right idea, @msdvcii. blob-select does not _do_ animation itself; that magic is entirely in CSS. In cases where more than one behavior are desired — based on e.g. relative placement within the screen or page — you'll definitely need to add modifier classes.

But for my own uses, I tend to place raw `<select>` elements inside static wrappers, applying modifier classes to the wrappers instead, like:
```html
<div class="select-wrapper upper">
    <select data-blobselect="{foo: bar}">...</select>
</div>
```

It's dealer's choice, but anything added directly to a generated `.blobselect` element might get wiped out if that instance is destroyed/rebuilt for any reason. Wrappers are also helpful when existence is controlled by a third-party library like Vue; you can put a `v-if` on the wrapper, but you can't put a `v-if` on the generated `.blobselect`. :wink: 

In terms of styles, modifier classes on a parent don't really change much. You'd just do `.upper > .blobselect { ... }` instead of `.blobselect.upper { ... }`.

**Comment by volcanioo** [comment]
I guess you are don't understand my problem. But, I share my fix theory, I will try to explain more clearly.

**Comment by joshstoik1** [comment]
Hi @msdvcii,

I believe I understand. You would like to have a blob-select's menu drop _up_ rather than drop down in cases where the element is close to the bottom of the screen or page. Is that correct?

The plugin itself — the Javascript library — does not control menu positioning or animations. Because all styling is left up to the user, it can't make any assumptions along those lines.

But if I had a project that needed up/down controls like you described, I would wrap each `<select>` field in a `<div class="select-wrapper">`, and bind a Javascript callback to the window's `scroll` event. That callback would look similar to what you suggested. It would loop through `document.querySelectorAll('.select-wrapper')` and set modifier classes like `animate-upward` or `animate-downward` depending on how close each element is to the bottom of the screen. On the CSS side, the animation definitions would be chained like:
```css
/* Global styles. */
.blobselect { ... }
/* Animate Menu Upward */
.select-wrapper.animate-upward > .blobselect { ... }
/* Animate Menu Downward */
.select-wrapper.animate-downward > .blobselect { ... }
```
